apiVersion: v1
kind: Service
metadata:
  name: spring-boot-rest
  labels:
    app: spring-boot-rest
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: app
    protocol: TCP
    targetPort: 8090
  - port: 8091
    name: operation
    protocol: TCP
    targetPort: 8091
  selector:
    app: spring-boot-rest