apiVersion: v1
kind: Service
metadata:
  name: spring-boot-rest
  labels:
    app: spring-boot-rest
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: spring-boot-rest